---
title: "Tarea 5"
output: html_notebook
---
# Pregunta 1
ProbaNDOOO
```{r}
if(!require("pacman")) install.packages("pacman")
p_load("tidyverse", "tidyquant", "WDI", "fBasics", "gridExtra", "grid", "scales", 
       "plyr", "extrafont", "zoo")
```

```{r}
tickers <- c("^GDAXI", "^FTSE")
data_activos <- tq_get(tickers,
                get = "stock.prices",
                from = "2005-01-01",
                to  = "2018-01-01",
                periodicity = "monthly")
retornos_activos <- data_activos %>%
                    group_by(symbol) %>%
                    tq_transmute(select = close,
                      mutate_fun = periodReturn,
                      period = "daily",
                      type = "log",
                      col_rename = "retornos.diarios")
retornos_activos %>%
         ggplot(mapping = aes(x = retornos.diarios, fill = symbol))+
         geom_density(alpha = 0.5) +
             labs(title = "Retornos Activos",
                  subtitle = "DAX Alemania & FTSE 100 Reino Unido",
                  x = "Retornos mensuales", y = "Densidad") +
         theme_tq() +
         scale_fill_tq() +
         facet_wrap(~ symbol, ncol = 2) +
         guides(fill=guide_legend(title="Activos:"))
```

